development: &development
  # rally credentials
  rally_username: 
  rally_password: 
  rally_workspace: 
  rally_api_version: 1.24
  # custom http headers - REST API
  custom_headers:
    name: "CodebaseHQ to Rally Connector"
    version: "Alpha1"
    vendor: "Abril Group"
  codebase_valid_file_changes: ["added", "modified", "removed"]

test:
  <<: *development

production:
  <<: *development
  
